/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.mma.probability;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int background=0x7f020000;
        public static final int codea=0x7f020001;
        public static final int ic_launcher=0x7f020002;
        public static final int image_1=0x7f020003;
        public static final int logoshadowedcopy=0x7f020004;
        public static final int schlogo=0x7f020005;
        public static final int sharelogo=0x7f020006;
    }
    public static final class id {
        public static final int by=0x7f060007;
        public static final int schlogo=0x7f060002;
        public static final int share=0x7f060008;
        public static final int shareBtn=0x7f060001;
        public static final int startBtn=0x7f060000;
        public static final int text1=0x7f060003;
        public static final int text2=0x7f060004;
        public static final int text3=0x7f060005;
        public static final int text4=0x7f060006;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int main2=0x7f030001;
        public static final int mainnew=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
    public static final class style {
        public static final int AppTheme=0x7f050000;
    }
}
